version: '3.9'
services:
  mongo:
    image: mongo:6
    container_name: vbc-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: vbc-server
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongo:27017/virtual_book_club}
      - PORT=${PORT:-4000}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:5173}
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      - mongo
    ports:
      - '4000:4000'

  client:
    build: ./client
    container_name: vbc-client
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:4000}
      - VITE_WS_URL=${VITE_WS_URL:-http://localhost:4000}
    ports:
      - '5173:5173'

volumes:
  mongo-data:
