name: CI

on:
  push:
    branches: [ main, master, develop, '**' ]
  pull_request:
    branches: [ main, master, develop, '**' ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install server deps
        run: npm ci
        working-directory: ./server

      - name: Lint server
        run: npm run lint --if-present
        working-directory: ./server

      - name: Test server (jest)
        run: npm test --if-present
        working-directory: ./server

      - name: Build server
        run: npm run build --if-present
        working-directory: ./server

      - name: Install client deps
        run: npm ci
        working-directory: ./client

      - name: Lint client
        run: npm run lint --if-present
        working-directory: ./client

      - name: Build client
        run: npm run build --if-present
        working-directory: ./client
